# Generated by Django 5.1.6 on 2025-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=50)),
                ('product_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField()),
                ('product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_row_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
